// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL?.trim();

// IMPORTANTE: Para Auth, usar SEMPRE a chave anon key (JWT), não a publishable key
// A chave publishable (sb_publishable_...) pode não funcionar corretamente com Auth
// Forçar uso da VITE_SUPABASE_ANON_KEY explicitamente
let SUPABASE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY?.trim();

// Se anon key não existir, usar publishable como fallback (mas pode causar problemas)
if (!SUPABASE_KEY) {
  console.warn('⚠️ VITE_SUPABASE_ANON_KEY não encontrada. Usando VITE_SUPABASE_PUBLISHABLE_KEY (pode não funcionar para Auth)');
  SUPABASE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY?.trim();
}

// Validar que a chave é válida (deve começar com 'eyJ' para JWT anon key)
if (SUPABASE_KEY && !SUPABASE_KEY.startsWith('eyJ') && !SUPABASE_KEY.startsWith('sb_publishable_')) {
  console.warn('⚠️ A chave Supabase pode estar em formato incorreto. Esperado: JWT (eyJ...) ou publishable (sb_publishable_...)');
}

// Debug: verificar se as variáveis estão sendo carregadas (apenas em desenvolvimento)
if (import.meta.env.DEV) {
  console.log('Supabase Config:', {
    url: SUPABASE_URL || '✗ Não definido',
    key: SUPABASE_KEY ? `✓ Definido (${SUPABASE_KEY.substring(0, 30)}...)` : '✗ Não definido',
    keyLength: SUPABASE_KEY?.length || 0,
    keyType: SUPABASE_KEY?.startsWith('sb_publishable_') ? 'Publishable' : SUPABASE_KEY?.startsWith('eyJ') ? 'Anon (JWT)' : 'Desconhecido',
    urlMatch: SUPABASE_URL?.includes('zlqpgxvmiqadavimqtns') ? '✓ URL correta' : '✗ URL incorreta',
    publishableKey: import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ? '✓ Presente' : '✗ Ausente',
    anonKey: import.meta.env.VITE_SUPABASE_ANON_KEY ? '✓ Presente' : '✗ Ausente',
    usingKey: import.meta.env.VITE_SUPABASE_ANON_KEY ? 'ANON_KEY' : 'PUBLISHABLE_KEY',
  });
}

if (!SUPABASE_URL || !SUPABASE_KEY) {
  const errorMsg = `Missing Supabase environment variables.
    VITE_SUPABASE_URL: ${SUPABASE_URL ? '✓' : '✗'}
    VITE_SUPABASE_PUBLISHABLE_KEY: ${import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ? '✓' : '✗'}
    VITE_SUPABASE_ANON_KEY: ${import.meta.env.VITE_SUPABASE_ANON_KEY ? '✓' : '✗'}
    
    Please ensure VITE_SUPABASE_URL and either VITE_SUPABASE_PUBLISHABLE_KEY or VITE_SUPABASE_ANON_KEY are set in your .env.local file.`;
  console.error(errorMsg);
  throw new Error(errorMsg);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});